export const fakeTitles = [
  'Changeling With Sins',
  'Duke Without A Goal',
  'Lions Of The World',
  'Blacksmiths Of Yesterday',
  'Traitors And Phantoms',
  'Boys And Traitors',
  'Cause Of Tomorrow',
  'Demise Of The North',
  'Changing The Demons',
  'Searching For Nature',
  'Fox Of Rain',
  'Ghost Of Sunshine',
  'Little Birds In My Town',
  'Bears Of Fantasia',
  'Kings And Little Dragons',
  'Cats And Owls',
  'Hat Of Fire',
  'Cup Of Mystery',
  'Jealous Of Flowers',
  'Amazing Life Of The Mountains',
  'Bear Of Tomorrow',
  'Little Dragon Of Gold',
  'Rabbits Of Miracles',
  'Boys Of Dreams',
  'Kids And Kittens',
  'Goats And Bunnies',
  'House Of Puzzles',
  'Chimney Of My Imagination',
  'Reading With My Friend',
  'Amazing World Of My Best Friend',
  'Boy Of Wonder',
  'Boy Of Utopia',
  'Foxes Of Fantasia',
  'Kings On The Moon',
  'Frogs And Babies',
  'Little Ducks And Kings',
  'Car Of Mysteries',
  'Field Of Wood',
  'Playing With My New Pet',
  'Playing With My Sister',
];

export const fakeWriters = [
  'billickin',
  'snittle',
  'tomkinley',
  'jefferson',
  'clarriker',
  'skewton',
  'smike',
  'newman',
  'ninetta',
  'lummy',
  'chollop',
  'sluffen',
  'sownds',
  'tappertit',
  'chevy',
  'chestle',
  'arethusa',
  'spyers',
  'compeyson',
  'defarge',
  'fibbitson',
  'flopson',
  'lavinia',
  'septimus',
  'curdle',
  'skettles',
  'blight',
  'chopkins',
  'gazingi',
  'kibble',
  'slum',
  'mortimer',
  'sleary',
  'brogson',
  'todd',
]

export const scenarioTextPlaceholder = 'The wild wolf fell into the example scenario text and was confused about what to do. The red fox jumped over the fence. Everyone expected some fat lorem ipsum but this is all they received';